---
abstract: 'Profile memory usage of requests'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Catalyst: 0
  Catalyst::Controller: 0
  File::Find: 0
  File::Temp: 0
  Module::Build: 0.3601
  Test::More: 0.88
  Test::WWW::Mechanize::Catalyst: 0
  parent: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-Plugin-MemoryUsage
provides:
  Catalyst::Plugin::MemoryUsage:
    file: lib/Catalyst/Plugin/MemoryUsage.pm
    version: v0.4.0
requires:
  Devel::CheckOS: 0
  List::Util: 0
  MRO::Compat: 0
  Memory::Usage: 0
  Moose::Role: 0
  Number::Bytes::Human: 0
  Text::SimpleTable: 0
  namespace::autoclean: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Catalyst-Plugin-MemoryUsage
  homepage: http://search.cpan.org/dist/Catalyst-Plugin-MemoryUsage/
  repository: https://github.com/yanick/Catalyst-Plugin-MemoryUsage.git
version: 0.4.0
x_author_pledge:
  version: 1
x_authority: cpan:YANICK
